apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka
  namespace: umbrella-streaming
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: umbrella
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  podMetricsEndpoints:
    - port: jmx-metrics
      path: /metrics
      interval: 30s
